version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database

  frontend:
    build:
      context: my-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  database:
    image: mongo
    ports:
      - "27017:27017"
